set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/s_axis_tlast_d1]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/s_axis_tvalid_d1_reg_n_0]

set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[0]}]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_key]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/trig_latch_clr]

set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/status[31]}]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tvalid_key]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tready_fc]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_fc]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tready_key]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/pass]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tready_sink]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tvalid_fc]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[10]}]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/s_axis_aresetn]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_fc]]


set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/m_axis_tlast]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/m_axis_tvalid]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/m_axis_tready]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[0]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[1]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[2]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[3]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[4]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[5]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[6]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[7]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[8]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[9]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[10]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[11]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[12]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[13]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[14]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_cnt[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[0]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[1]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[2]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[3]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[4]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[5]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[6]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[7]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[8]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[9]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[10]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[11]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[12]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[13]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[14]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[15]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[16]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[17]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[18]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[19]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[20]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[21]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[22]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[23]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[24]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[25]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[26]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[27]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[28]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[29]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[30]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/axis_fifo_fc_count[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[0]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[1]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[2]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[0]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[1]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[2]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/axis_flow_control_d1_0/U0/status[0]} {design_1_i/axis_flow_control_d1_0/U0/status[1]} {design_1_i/axis_flow_control_d1_0/U0/status[2]} {design_1_i/axis_flow_control_d1_0/U0/status[3]} {design_1_i/axis_flow_control_d1_0/U0/status[4]} {design_1_i/axis_flow_control_d1_0/U0/status[5]} {design_1_i/axis_flow_control_d1_0/U0/status[6]} {design_1_i/axis_flow_control_d1_0/U0/status[7]} {design_1_i/axis_flow_control_d1_0/U0/status[8]} {design_1_i/axis_flow_control_d1_0/U0/status[9]} {design_1_i/axis_flow_control_d1_0/U0/status[10]} {design_1_i/axis_flow_control_d1_0/U0/status[11]} {design_1_i/axis_flow_control_d1_0/U0/status[12]} {design_1_i/axis_flow_control_d1_0/U0/status[13]} {design_1_i/axis_flow_control_d1_0/U0/status[14]} {design_1_i/axis_flow_control_d1_0/U0/status[15]} {design_1_i/axis_flow_control_d1_0/U0/status[16]} {design_1_i/axis_flow_control_d1_0/U0/status[17]} {design_1_i/axis_flow_control_d1_0/U0/status[18]} {design_1_i/axis_flow_control_d1_0/U0/status[19]} {design_1_i/axis_flow_control_d1_0/U0/status[20]} {design_1_i/axis_flow_control_d1_0/U0/status[21]} {design_1_i/axis_flow_control_d1_0/U0/status[22]} {design_1_i/axis_flow_control_d1_0/U0/status[23]} {design_1_i/axis_flow_control_d1_0/U0/status[24]} {design_1_i/axis_flow_control_d1_0/U0/status[25]} {design_1_i/axis_flow_control_d1_0/U0/status[26]} {design_1_i/axis_flow_control_d1_0/U0/status[27]} {design_1_i/axis_flow_control_d1_0/U0/status[28]} {design_1_i/axis_flow_control_d1_0/U0/status[29]} {design_1_i/axis_flow_control_d1_0/U0/status[30]} {design_1_i/axis_flow_control_d1_0/U0/status[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/m_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tlast_key]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/m_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tready_fc]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tready_key]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tready_sink]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/m_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tvalid_fc]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/m_axis_tvalid_key]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/pass]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/s_axis_aresetn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/s_axis_tlast_d1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/s_axis_tvalid_d1_reg_n_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/trig_latch_clr]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK1]
