set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[3]}]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/trig_latch_clr]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/trig_latch]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/status[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/status[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/status[18]}]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/release]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[0]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[1]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[2]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[0]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[1]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[2]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[3]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[4]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[5]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[6]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[7]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[8]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[9]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[10]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[11]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[12]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[13]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[14]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[15]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[16]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[17]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[18]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[19]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[20]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[21]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[22]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[23]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[24]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[25]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[26]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[27]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[28]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[29]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[30]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/gtu_sig_counter_i[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[0]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[1]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[2]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/sm_state_sink[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/status[8]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/status[9]} {design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/status[18]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/axi_data_provider_z3_0_FRAME]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/release]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/trig_latch]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axis_flow_control_d1_0/U0/i_flow_control_d1/trig_latch_clr]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
