

set_property MARK_DEBUG true [get_nets design_1_i/axi_cathode_ctrl_0/U0/DATA_HV]
set_property MARK_DEBUG true [get_nets design_1_i/axi_cathode_ctrl_0/U0/CLK_HV]
set_property MARK_DEBUG true [get_nets design_1_i/axi_cathode_ctrl_0/U0/GTU_HV]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_z3_0_ec_sig_out[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_z3_0_ec_sig_out[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_z3_0_ec_sig_out[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_z3_0_ec_sig_out[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_z3_0_ec_sig_out[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_z3_0_ec_sig_out[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_z3_0_ec_sig_out[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_z3_0_ec_sig_out[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_z3_0_ec_sig_out[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[55]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[56]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[58]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[61]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[36]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[34]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[32]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[47]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[37]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[49]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[51]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[54]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[44]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[42]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[40]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[53]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[45]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[35]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[33]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[57]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[63]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[60]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[62]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[59]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[46]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[48]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[52]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[38]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[43]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[41]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[39]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[50]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[12]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 64 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[0]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[1]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[2]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[3]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[4]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[5]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[6]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[7]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[8]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[9]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[10]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[11]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[12]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[13]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[14]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[15]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[16]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[17]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[18]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[19]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[20]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[21]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[22]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[23]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[24]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[25]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[26]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[27]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[28]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[29]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[30]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[31]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[32]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[33]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[34]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[35]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[36]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[37]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[38]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[39]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[40]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[41]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[42]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[43]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[44]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[45]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[46]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[47]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[48]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[49]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[50]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[51]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[52]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[53]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[54]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[55]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[56]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[57]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[58]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[59]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[60]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[61]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[62]} {design_1_i/axis_flow_control_d1_0_unix_time_ngtu[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[0]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[1]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[2]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[3]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[4]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[5]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[6]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[7]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[8]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[9]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[10]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[11]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[12]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[13]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[14]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[15]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[16]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[17]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[18]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[19]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[20]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[21]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[22]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[23]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[24]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[25]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[26]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[27]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[28]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[29]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[30]} {design_1_i/axis_data_fifo_mps_M_AXIS_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[32]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[33]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[34]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[35]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[36]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[37]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[38]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[39]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[40]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[41]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[42]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[43]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[44]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[45]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[46]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[47]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[48]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[49]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[50]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[51]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[52]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[53]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[54]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[55]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[56]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[57]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[58]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[59]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[60]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[61]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[62]} {design_1_i/axis_broadcaster_0_M01_AXIS_TDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 9 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/axi_data_provider_z3_0_ec_sig_out[0]} {design_1_i/axi_data_provider_z3_0_ec_sig_out[1]} {design_1_i/axi_data_provider_z3_0_ec_sig_out[2]} {design_1_i/axi_data_provider_z3_0_ec_sig_out[3]} {design_1_i/axi_data_provider_z3_0_ec_sig_out[4]} {design_1_i/axi_data_provider_z3_0_ec_sig_out[5]} {design_1_i/axi_data_provider_z3_0_ec_sig_out[6]} {design_1_i/axi_data_provider_z3_0_ec_sig_out[7]} {design_1_i/axi_data_provider_z3_0_ec_sig_out[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/axis_broadcaster_0_M01_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axis_broadcaster_0_M01_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/axis_broadcaster_0_M01_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axis_data_fifo_mps_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/axis_data_fifo_mps_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/axis_data_fifo_mps_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/axi_cathode_ctrl_0/U0/CLK_HV]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/axi_cathode_ctrl_0/U0/DATA_HV]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/axi_cathode_ctrl_0/U0/GTU_HV]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK1]
