set_property MARK_DEBUG true [get_nets design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/cs_dac]
set_property MARK_DEBUG true [get_nets design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/cs_exp]
set_property MARK_DEBUG true [get_nets design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/mosi]
set_property MARK_DEBUG true [get_nets design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/sck]
set_property MARK_DEBUG true [get_nets design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/miso]
set_property MARK_DEBUG true [get_nets {design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/D[0]}]

set_property MARK_DEBUG true [get_nets design_1_i/axi_cathode_ctrl_0/U0/DATA_HV]
set_property MARK_DEBUG true [get_nets design_1_i/axi_cathode_ctrl_0/U0/CLK_HV]
set_property MARK_DEBUG true [get_nets design_1_i/axi_cathode_ctrl_0/U0/GTU_HV]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/D[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/axi_cathode_ctrl_0/U0/CLK_HV]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/cs_dac]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/cs_exp]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/axi_cathode_ctrl_0/U0/DATA_HV]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axi_cathode_ctrl_0/U0/GTU_HV]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/miso]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/mosi]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/hv_hk_v1_0_0/U0/hv_hk_v1_0_S00_AXI_inst/sck]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK1]