set_property PACKAGE_PIN Y13 [get_ports {Dout_Art[0]}]
set_property PACKAGE_PIN Y11 [get_ports {Dout_Zynq[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Dout_Zynq[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Dout_Art[0]}]

set_property PACKAGE_PIN Y11 [get_ports {Dout_3[0]}]
set_property PACKAGE_PIN AF10 [get_ports {Dout_2[0]}]
set_property PACKAGE_PIN AF15 [get_ports {Dout_1[0]}]
set_property PACKAGE_PIN AF17 [get_ports {Dout_0[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Dout_0[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Dout_1[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Dout_2[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Dout_3[0]}]

set_property PACKAGE_PIN H13 [get_ports {data_in_from_pins_p_0[11]}]
set_property PACKAGE_PIN K15 [get_ports {data_in_from_pins_p_0[10]}]
set_property PACKAGE_PIN F13 [get_ports {data_in_from_pins_p_0[9]}]
set_property PACKAGE_PIN G16 [get_ports {data_in_from_pins_p_0[8]}]
set_property PACKAGE_PIN K13 [get_ports {data_in_from_pins_p_0[7]}]
set_property PACKAGE_PIN G12 [get_ports {data_in_from_pins_p_0[6]}]
set_property PACKAGE_PIN J14 [get_ports {data_in_from_pins_p_0[5]}]
set_property PACKAGE_PIN G14 [get_ports {data_in_from_pins_p_0[4]}]
set_property PACKAGE_PIN C14 [get_ports {data_in_from_pins_p_0[3]}]
set_property PACKAGE_PIN C17 [get_ports {data_in_from_pins_p_0[2]}]
set_property PACKAGE_PIN B16 [get_ports {data_in_from_pins_p_0[1]}]
set_property PACKAGE_PIN B17 [get_ports {data_in_from_pins_p_0[0]}]
set_property PACKAGE_PIN F12 [get_ports {data_in_from_pins_p_0[12]}]
set_property PACKAGE_PIN D15 [get_ports CLK_IN_D_0_clk_p]
set_property IOSTANDARD LVDS [get_ports CLK_IN_D_0_clk_p]

create_clock -period 2.500 -name CLK_IN_D_0_clk_p -waveform {0.000 1.250} [get_ports CLK_IN_D_0_clk_p]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
