// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_scurve_adder (
hls::stream<struct ap_axis<16, 2, 5, 6 > > (&in_stream0),
hls::stream<struct ap_axis<64, 2, 5, 6 > > (&out_stream),
unsigned short N_ADDS);
